postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: "test"
    username: "daniel"
    password: "test"
    database: "mydb"
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.3.0-debian-12-r23
  primary:
    persistence:
      enabled: true
      existingClaim: "postgresql-pv-claim"
      size: 10Gi
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      runAsUser: 1001
  volumePermissions:
    enabled: true

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: { }

ingress-nginx:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: prometheus
        enabled: true
    allowSnippetAnnotations: "true"
