<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FeedController' shared autowired service.
     *
     * @return \App\Controller\FeedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FeedController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FeedService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseService.php';

        $container->services['App\\Controller\\FeedController'] = $instance = new \App\Controller\FeedController(new \App\Service\FeedService(($container->privates['redis'] ?? $container->load('getRedisService')), ($container->privates['App\\Service\\DatabaseService'] ?? ($container->privates['App\\Service\\DatabaseService'] = new \App\Service\DatabaseService($container->getEnv('resolve:DATABASE_URL'))))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.SDLTfYt'] ?? $container->load('get_ServiceLocator_SDLTfYtService'))->withContext('App\\Controller\\FeedController', $container));

        return $instance;
    }
}
