<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_AddPostsConsumerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'old_sound_rabbit_mq.add_posts_consumer' shared service.
     *
     * @return \OldSound\RabbitMqBundle\RabbitMq\Consumer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/BaseAmqp.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/DequeuerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/BaseConsumer.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/ConsumerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Consumer/AddPosts/Consumer.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseService.php';

        $container->services['old_sound_rabbit_mq.add_posts_consumer'] = $instance = new \OldSound\RabbitMqBundle\RabbitMq\Consumer(($container->services['old_sound_rabbit_mq.connection.default'] ?? $container->load('getOldSoundRabbitMq_Connection_DefaultService')));

        $instance->setExchangeOptions(['name' => 'old_sound_rabbit_mq.add_posts', 'type' => 'direct', 'passive' => false, 'durable' => true, 'auto_delete' => false, 'internal' => false, 'nowait' => false, 'declare' => true, 'arguments' => NULL, 'ticket' => NULL]);
        $instance->setQueueOptions(['name' => 'old_sound_rabbit_mq.consumer.add_posts', 'passive' => false, 'durable' => true, 'exclusive' => false, 'auto_delete' => false, 'nowait' => false, 'declare' => true, 'arguments' => NULL, 'ticket' => NULL, 'routing_keys' => []]);
        $instance->setCallback([0 => new \App\Consumer\AddPosts\Consumer(($container->privates['App\\Service\\DatabaseService'] ?? ($container->privates['App\\Service\\DatabaseService'] = new \App\Service\DatabaseService($container->getEnv('resolve:DATABASE_URL')))), ($container->privates['redis'] ?? $container->load('getRedisService'))), 1 => 'execute']);
        $instance->setQosOptions(0, 1, false);
        $instance->setIdleTimeout(300);
        $instance->setIdleTimeoutExitCode(0);
        $instance->setGracefulMaxExecutionDateTimeFromSecondsInTheFuture(1800);
        $instance->setGracefulMaxExecutionTimeoutExitCode(0);
        if ($container->has('event_dispatcher')) {
            $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        }

        return $instance;
    }
}
