<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_AnonConsumerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'old_sound_rabbit_mq.anon_consumer_command' shared service.
     *
     * @return \OldSound\RabbitMqBundle\Command\AnonConsumerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/Command/BaseRabbitMqCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/Command/AnonConsumerCommand.php';

        $container->privates['old_sound_rabbit_mq.anon_consumer_command'] = $instance = new \OldSound\RabbitMqBundle\Command\AnonConsumerCommand();

        $instance->setContainer($container);
        $instance->setName('rabbitmq:anon-consumer');

        return $instance;
    }
}
