<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_Connection_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'old_sound_rabbit_mq.connection.default' shared service.
     *
     * @return \PhpAmqpLib\Connection\AMQPStreamConnection
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/AMQPConnectionFactory.php';

        return $container->services['old_sound_rabbit_mq.connection.default'] = (new \OldSound\RabbitMqBundle\RabbitMq\AMQPConnectionFactory('PhpAmqpLib\\Connection\\AMQPStreamConnection', ['url' => $container->getEnv('RABBITMQ_URL'), 'host' => 'localhost', 'port' => 5672, 'user' => 'guest', 'password' => 'guest', 'vhost' => '/', 'login_method' => 'AMQPLAIN', 'hosts' => [], 'lazy' => false, 'connection_timeout' => 3, 'read_write_timeout' => 3, 'channel_rpc_timeout' => 0.0, 'use_socket' => false, 'ssl_context' => [], 'keepalive' => false, 'heartbeat' => 0]))->createConnection();
    }
}
