<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PostController' shared autowired service.
     *
     * @return \App\Controller\PostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PostController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AsyncService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseService.php';

        $a = new \App\Service\AsyncService();
        $a->registerProducer('add_post', ($container->services['old_sound_rabbit_mq.add_posts_producer'] ?? $container->load('getOldSoundRabbitMq_AddPostsProducerService')));

        $container->services['App\\Controller\\PostController'] = $instance = new \App\Controller\PostController(($container->privates['App\\Service\\DatabaseService'] ?? ($container->privates['App\\Service\\DatabaseService'] = new \App\Service\DatabaseService($container->getEnv('resolve:DATABASE_URL')))), $a, ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.SDLTfYt'] ?? $container->load('get_ServiceLocator_SDLTfYtService'))->withContext('App\\Controller\\PostController', $container));

        return $instance;
    }
}
