<?php

namespace ContainerGuXJN1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserController' shared autowired service.
     *
     * @return \App\Controller\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseService.php';

        $container->services['App\\Controller\\UserController'] = $instance = new \App\Controller\UserController(($container->privates['App\\Service\\DatabaseService'] ?? ($container->privates['App\\Service\\DatabaseService'] = new \App\Service\DatabaseService($container->getEnv('resolve:DATABASE_URL')))));

        $instance->setContainer(($container->privates['.service_locator.SDLTfYt'] ?? $container->load('get_ServiceLocator_SDLTfYtService'))->withContext('App\\Controller\\UserController', $container));

        return $instance;
    }
}
