<?php

namespace ContainerWmYj4Pp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_Command_StdInProducerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'old_sound_rabbit_mq.command.std_in_producer_command' shared service.
     *
     * @return \OldSound\RabbitMqBundle\Command\StdInProducerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/Command/BaseRabbitMqCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/Command/StdInProducerCommand.php';

        $container->privates['old_sound_rabbit_mq.command.std_in_producer_command'] = $instance = new \OldSound\RabbitMqBundle\Command\StdInProducerCommand();

        $instance->setContainer($container);
        $instance->setName('rabbitmq:stdin-producer');

        return $instance;
    }
}
