<?php

namespace ContainerWmYj4Pp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_PartsHolderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'old_sound_rabbit_mq.parts_holder' shared service.
     *
     * @return \OldSound\RabbitMqBundle\RabbitMq\AmqpPartsHolder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/AmqpPartsHolder.php';

        $container->services['old_sound_rabbit_mq.parts_holder'] = $instance = new \OldSound\RabbitMqBundle\RabbitMq\AmqpPartsHolder();

        $a = ($container->services['old_sound_rabbit_mq.add_posts_producer'] ?? $container->load('getOldSoundRabbitMq_AddPostsProducerService'));
        $b = ($container->services['old_sound_rabbit_mq.add_posts_consumer'] ?? $container->load('getOldSoundRabbitMq_AddPostsConsumerService'));

        $instance->addPart('old_sound_rabbit_mq.base_amqp', $a);
        $instance->addPart('old_sound_rabbit_mq.base_amqp', $b);
        $instance->addPart('old_sound_rabbit_mq.producer', $a);
        $instance->addPart('old_sound_rabbit_mq.consumer', $b);

        return $instance;
    }
}
