<?php

namespace ContainerWmYj4Pp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\User\UserProvider' shared autowired service.
     *
     * @return \App\Security\User\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/PasswordUpgraderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/User/UserProvider.php';

        $a = new \PDO('pgsql:host='.$container->getEnv('string:POSTGRES_HOST').';port='.$container->getEnv('string:POSTGRES_PORT').';dbname='.$container->getEnv('string:POSTGRES_DB'), $container->getEnv('POSTGRES_USER'), $container->getEnv('POSTGRES_PASSWORD'));
        $a->setAttribute(3, 2);

        return $container->privates['App\\Security\\User\\UserProvider'] = new \App\Security\User\UserProvider($a);
    }
}
