version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver_chat
    ports:
      - "80:80"
    volumes:
      - .:/data
    networks:
      - pgnet

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app_chat
    volumes:
      - .:/data
    networks:
      - pgnet

  postgresql:
    image: postgres:latest
    container_name: postgres_chat
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnet


volumes:
  pgdata:

networks:
  pgnet:
    driver: bridge
