<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmYj4Pp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmYj4Pp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWmYj4Pp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWmYj4Pp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWmYj4Pp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WmYj4Pp',
    'container.build_id' => 'b10327ce',
    'container.build_time' => 1728072451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmYj4Pp');
