<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'get_feed' => [[], ['_controller' => 'App\\Controller\\FeedController::getFeed'], [], [['text', '/api/feed']], [], [], []],
    'add_post' => [[], ['_controller' => 'App\\Controller\\PostController::createPost'], [], [['text', '/api/post']], [], [], []],
    'register_user' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/api/register']], [], [], []],
    'search_users' => [[], ['_controller' => 'App\\Controller\\RegistrationController::searchUsers'], [], [['text', '/api/user/search']], [], [], []],
    'get_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::getUserById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/user/get']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
